config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  resources :twitters do
    member do
      get 'preview'
    end
    collection do
      get 'search'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "twitters#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/twitter.rb
class Twitter < ApplicationRecord
     include PgSearch::Model
        pg_search_scope :search_full_text,
        against: {
                    username: 'A',
                    description:'B',
                    id:"C"
            }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
    Pagy::DEFAULT[:limit] = 10 # items per page
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
  before_action :set_twitter, only: %i[ show edit update destroy ]

  # GET /twitters or /twitters.json
  def index
    
    @pagy, @twitters = pagy(Twitter.all)
    if params[:query_text].present?
      @twitters = @twitters.search_full_text(params[:query_text])
    end
  end

  # GET /twitters/1 or /twitters/1.json
  def show
  end

  def preview
  end

  def search
  end

  # GET /twitters/new
  def new
    @twitter = Twitter.new
  end

  # GET /twitters/1/edit
  def edit
  end

  # POST /twitters or /twitters.json
  def create
    @twitter = Twitter.new(twitter_params)

    respond_to do |format|
      if @twitter.save
        format.html { redirect_to twitter_url(@twitter), notice: "Twitter was successfully created." }
        format.json { render :show, status: :created, location: @twitter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @twitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twitters/1 or /twitters/1.json
  def update
    respond_to do |format|
      if @twitter.update(twitter_params)
        format.html { redirect_to twitter_url(@twitter), notice: "Twitter was successfully updated." }
        format.json { render :show, status: :ok, location: @twitter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @twitter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twitters/1 or /twitters/1.json
  def destroy
    @twitter.destroy!

    respond_to do |format|
      format.html { redirect_to twitters_url, notice: "Twitter was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twitter
      @twitter = Twitter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twitter_params
      params.require(:twitter).permit(:username, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/twitters_helper.rb
module TwittersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/twitters/_form.html.erb
<%= form_with(model: twitter) do |form| %>
  <% if twitter.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(twitter.errors.count, "error") %> prohibited this twitter from being saved:</h2>

      <ul>
        <% twitter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/twitters/_twitter.html.erb
<div id="<%= dom_id twitter %>">
  <p>
      <strong>Id:</strong>
    <%= twitter.id %>
  </p>
  <p>
    <strong>Username:</strong>
    <%= twitter.username %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= twitter.description %>
  </p>

</div>

app/views/twitters/edit.html.erb
<h1>Editing twitter</h1>

<%= render "form", twitter: @twitter %>

<br>

<div>
  <%= link_to "Show this twitter", @twitter %> |
  <%= link_to "Back to twitters", twitters_path %>
</div>

app/views/twitters/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Twitter</h1>
<br>
<div id="twitters">

<%= form_with url: twitters_path, method: :get do |form|%>
 <%= form.text_field :query_text, placeholder: "Buscar tweet", value: params[:query_text],class: "form-control"%>
<%end%>
<br>

  <% @twitters.each do |twitter| %>
    <%= render twitter %>
    <p>
      <%= link_to "Show this twitter", twitter %>
    </p>
  <% end %>
</div>

<%=raw pagy_nav(@pagy)%>


<%= link_to "New twitter", new_twitter_path %>

app/views/twitters/new.html.erb
<h1>New twitter</h1>

<%= render "form", twitter: @twitter %>

<br>

<div>
  <%= link_to "Back to twitters", twitters_path %>
</div>

app/views/twitters/preview.html.erb
<h1><Visata previa Tweet/h1>
<h2>ID: <%= params[:id]%></h2>

app/views/twitters/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @twitter %>

<div>
  <%= link_to "Edit this twitter", edit_twitter_path(@twitter) %> |
  <%= link_to "Back to twitters", twitters_path %>

  <%= button_to "Destroy this twitter", @twitter, method: :delete %>
</div>